### ISSUE TITLE
Inverted normals, metal/gloss not appearing as expected.

### ISSUE THREAD

**Issue by jehinrichs** [playcanvas/playcanvas-gltf#13]
Will,

Added an example of a glb I created in Modo.  It's a glTF 2.0 file.  Tested this at:

https://sandbox.babylonjs.com/
https://gltf-viewer.donmccurdy.com/
and on Facebook and I'm getting pretty consistent results there.

Using the PlayCanvas viewer app the model is appearing but the normals seem to be inverted and the metal/gloss isn't appearing correctly across the various materials in the model.  I enclosed the files.

[shoe.zip](https://github.com/playcanvas/playcanvas-gltf/files/1907768/shoe.zip)

**Comment by willeastcott** [comment]
I think I've improved matters.

![image](https://user-images.githubusercontent.com/697563/38764352-e03e1e9c-3f61-11e8-8f89-2c71674c0007.png)

**Comment by cx20** [comment]
@willeastcott I made a comparison with the following libraries. PlayCanvas seems to have black shoes. Is it because IBL or light setting is different?

Three.js + shoe.glb result:
![image](https://user-images.githubusercontent.com/1833979/38896377-7cad028e-42cd-11e8-98bb-3602fa452bfa.png)

Babylon.js + shoe.glb result:
![image](https://user-images.githubusercontent.com/1833979/38896383-80f3083e-42cd-11e8-8d95-843499d834ef.png)

PlayCanvas + shoe.glb result:
![image](https://user-images.githubusercontent.com/1833979/38896450-b26e3b7c-42cd-11e8-946d-a9cee297a6d8.png)

@jehinrichs This model is very interesting. If there is no problem with the license, will it be possible to provide it as a sample in Khornos' glTF Sample repository?
https://github.com/KhronosGroup/glTF-Sample-Models

**Comment by willeastcott** [comment]
The material definition in the glb file is:

![image](https://user-images.githubusercontent.com/697563/38899704-a60ad35c-424d-11e8-946c-72d2a431c4d4.png)

As you can see, the baseColorFactor values are tiny - essentially a _very_ dark brown. I don't know why the rendering for Babylon and Three have brought the brightness of the color up. @jehinrichs, as the author of the model (presumably), what result were you aiming for? To be honest, the diffuse texture is a bit weird. Almost looks like an AO map.

**Comment by emadurandal** [comment]
@willeastcott 

Hello, My name is Yuki Shimada, a friend of @cx20 . I'm a 3D developer ( 'GLBoost' WebGL library author).

> To be honest, the diffuse texture is a bit weird. Almost looks like an AO map.

You mean the 'Shoe_Shell_Diff.jpg'?
According to [glTF2.0 Spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material), colors of baseColorTexture and baseColorFactor will be multiplied. So in this shoe data, the creator of this may have controlled the 'color' of albedo by baseColorFactor, and controlled the 'intensity' of albedo by this 'Shoe_Shell_Diff.jpg', I guess.

But, I have no idea why the results of Three.js and Babylon.js looks like so bright. (The source code reviews are needed if we want the cause.)
I think that the result of PlayCanvas is rather close to the truth, maybe.

Anyway, at the present time, The world's WebGL libraries are still developing in PBR support.
So It is a good idea to find a reliable reference renderer. (For example, Arnold Renderer, Unreal Engine, etc...)

I think that raising a problem to the dev community of each WebGL library about the reproducibility of PBR is certainly a good thing for the whole. 😉

**Comment by emadurandal** [comment]
> I think that the result of PlayCanvas is rather close to the truth, maybe.

It may be my mere thought. After all, it is necessary to investigate carefully.

**Comment by jehinrichs** [comment]
Will,
Right...what Yuki was saying above, I'm using a greyscale and then 'multiplying' vs. the background color.  The idea being I can change the shoe color and the darkening around the front of the shoe and around the sides of the shoe will be retained no matter what color the shoe is

This is the same kinda deal you can do in PlayCanvas with the tint option.

**Comment by jehinrichs** [comment]
cx20, 

I have no problem with the shoe being included in the Khronos collection.  It was a test I did to show a client how a shoe similar to his product could look.

The shoe data came from a scan.  I retopoed it in Modo but I had to handpaint the normal maps, ao maps, and diffuse because the scan data was rough.   The shoe I used was a 'Stacy Adams' brand that my boss picked up at a store nearby, so I included the logo into the diffuse maps and a stencil map for the logo inside the shoe.  If the logos are a rights issue let me know and I can get you a version without any 'Stacy Adams' text.

P.S. I also used Modo newly included glTF support to export the glTF and glb files.

**Comment by jehinrichs** [comment]
Will,

Right, Yuki described what I was doing.  It's similar to the way PlayCanvas does the 'tint'...I used a greyscale to show where the shoe was meant to be stained darker and then dialed in the diffuse as a RGB value.  The idea being if a client wanted to show multiple shades of the same shoe we could do that easier programmatically.

**Comment by emadurandal** [comment]
I'm sorry for overriding my opinion, but the brightness of Three.js and Babylon.js may be more appropriate.

This is a preview in Unreal Engine 4.
![image](https://user-images.githubusercontent.com/3821214/38909300-09db2aba-42ff-11e8-9409-1b930c8e3321.png)

And this is the preview of baseColorFactor constant value of the 'Shoe' part.
![image](https://user-images.githubusercontent.com/3821214/38909393-6abb8e74-42ff-11e8-9a48-978bb5666b81.png)

This is ... contrary to the impression received from the small number, it is much brighter.
I don't know that UE4 handles gamma in material preview. At least, I think that baseColorFactor is linear value, maybe. Actually, linear values is more effective than sRGB (like JPG) values (because after conversion to linear, ofcourse these sRGB values are evaluated smaller.).

And our human's eyes have some gamma (maybe around 0.45, so we feel dark colors brighter than the truth. This is the cause of confusion.)

About the difference in the result's brightness of each library, one possible cause may be gamma handling.

**Comment by emadurandal** [comment]
(As reference information)

Due to Humans eyes' gamma, we feel bright from the intensity of (0.5, 0.5, 0.5).
![image](https://user-images.githubusercontent.com/3821214/38910183-214ed88c-4303-11e8-9056-fe42d7cafb1e.png)

The brightness that we feel it as medium gray is around (0.18, 0.18, 0.18) aka "18% gray".
![image](https://user-images.githubusercontent.com/3821214/38910088-ae716c76-4302-11e8-9d18-e304dc18f0fc.png)

**Comment by cx20** [comment]
@jehinrichs If you can cooperate with providing sample models, please PR the following contents to [glTF-Sample-Models](glTF-Sample-Models).
I will confirm the display with other libraries by [gltf-test](https://github.com/cx20/gltf-test) after PR is issued.

1. glTF Model

> https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ ModelName
> /README.md
> /screenshot/screenshot.jpg   ... screenshot 
> /glTF/ModelName.gltf       ... glTF Model
> /glTF-Binary/ModelName.glb ... glTF-Binary model

2. Source Model

> https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/ ModelName
> /README.md

3. glTF Validator

> It is recommended that models be verified with glTF-Validator.
> http://github.khronos.org/glTF-Validator/

**Comment by willeastcott** [comment]
OK, the problem was that PlayCanvas' pc.StandardMaterial expects you to set colors in sRGB space, whereas glTF supplies them in linear space. Using Math.pow(colorChannel, 1 / 2.2); fixes the problem:

![image](https://user-images.githubusercontent.com/697563/38939240-5284096c-42dc-11e8-82d7-61bf0ba3d24b.png)
