### ISSUE TITLE
AnimationSession for curves

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#70]
Hi, can anybody explain what the point is for an `AnimationSession` on every single `AnimationCurve`?

The code is already resource intensive (spawning 64 models uses like > 900 MB):

![image](https://user-images.githubusercontent.com/5236548/54073997-c685f300-428d-11e9-8e6b-aa0441ba9f66.png)

But if I comment out the `AnimationSession` in the curve constructor:

```
var AnimationCurve = function () {
    AnimationCurve.count ++;
    this.name = "curve" + AnimationCurve.count.toString();
    this.type = AnimationCurveType.LINEAR;
    this.keyableType = AnimationKeyableType.NUM;
    this.tension = 0.5;// 0.5 catmul-rom
    this.animTargets = [];// allow multiple targets
    this.duration = 0;
    this.animKeys = [];
    //this.session = new AnimationSession(this);
};
```

Then the code is using consistently like 100 MB less for the same scene:

![image](https://user-images.githubusercontent.com/5236548/54074043-372d0f80-428e-11e9-902f-91105a0e1adb.png)

I tested multiple models and blending between clips and everything still works. Why does each curve need a session?

**Comment by willeastcott** [comment]
I'm sure @thomasbiang can provide some information on this topic... 😄

**Comment by ywangsc** [comment]
Hi,
Originally each AnimationCurve has a default session, so that user can play animation on a single curve. For the same reason each AnimationClip also has a default session. If few people are using the API for playing a single curve and it takes up a lot resources, I can remove this default session.

**Comment by thomasbiang** [comment]
Hi,
Originally each AnimationCurve has a default session, so that user can play animation on a single curve. For the same reason each AnimationClip also has a default session. If few people are using the API for playing a single curve and it takes up a lot resources, I can remove this default session.

**Comment by kungfooman** [comment]
Hi, I feel it would make the code easier to understand, since it doesn't need any specialcasing via `instanceof` then and it removes some redundant code, which is needed to implement `Playable`. And if somebody just wants to animate one curve, its still easy enough to make a clip for it.

I would vote for removal, but this isn't a democracy here I guess ^^

**Comment by thomasbiang** [comment]
I made a pull request for this https://github.com/playcanvas/playcanvas-gltf/pull/72
